apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: springcloud
  labels:
    framework: springcloud
    app: springcloud-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      springcloud: eureka
  template:
    metadata:
      labels:
        springcloud: eureka
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '8761'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
        - name: app
          image: kshwnahr/eureka:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: active.profiles
            - name: spring.cloud.config.uri
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: config.host
            - name: eureka.datacenter
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: eureka.datacenter
            - name: eureka.environment
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: eureka.environment
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: springcloud
spec:
  selector:
    springcloud: eureka
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: NodePort
  #externalIPs: - 192.168.0.10
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: eureka
  namespace: springcloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eureka
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
