apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: springcloud
  labels:
    framework: springcloud
    app: springcloud-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      springcloud: eureka
  template:
    metadata:
      labels:
        springcloud: eureka
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '8761'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
        - name: app
          image: kshwnahr/eureka-server:amds
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: active.profiles
            - name: spring.cloud.config.uri
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: config.host
            - name: eureka.datacenter
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: eureka.datacenter
            - name: eureka.environment
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: eureka.environment
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: springcloud
spec:
  selector:
    springcloud: eureka
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: NodePort
  #externalIPs: - 192.168.0.10
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: eureka
  namespace: springcloud
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`eureka.kt.geniecube.io`)
    kind: Rule
    services:
    - name: eureka
      port: 8761
  tls:
    opetions:
      namespace: springcloud
    certResolver: le
    domains:
    - main: eureka.kt.geniecube.io
---

apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: eureka
  namespace: springcloud
spec:
  endpoints:
  - dnsName: eureka.kt.geniecube.io
    recordTTL: 180
    recordType: CNAME
    targets:
    - kt.geniecube.io
